package com.between_freedom_and_space.mono_backend.access.service.impl

import com.between_freedom_and_space.mono_backend.access.service.InformationAccessRulesService

class InformationAccessRulesServiceImpl: InformationAccessRulesService {
}