package com.between_freedom_and_space.mono_backend.access.repository.impl

import com.between_freedom_and_space.mono_backend.access.repository.CommonAccessedRolesRepository

class CommonAccessedRolesRepositoryImpl: CommonAccessedRolesRepository {
}