apapiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mono-backend-auto-scaler
  labels:
    app: mono-backend
    owner: Ferum-bot
    tier: backend
    stage: testing
    infrastructure: kotlin
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: mono-backend-deployment
    minReplicas: 2
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80