package com.between_freedom_and_space.mono_backend.posts.internal.reactions.modules.qualifiers

enum class ReactionsMappersQualifiers {
    COMMENT_REACTION_TO_BASE_MODEL,
    POST_REACTION_TO_BASE_MODEL,
    CREATE_COMMENT_REACTION_REQUEST_TO_MODEL,
    CREATE_POST_REACTION_REQUEST_TO_MODEL,
    UPDATE_COMMENT_REACTION_REQUEST_TO_MODEL,
    UPDATE_POST_REACTION_REQUEST_TO_MODEL,
    BASE_COMMENT_REACTION_TO_MODEL,
    BASE_POST_REACTION_TO_MODEL;
}