package com.between_freedom_and_space.mono_backend.posts.modules.qualifiers

enum class PostMappersQualifiers {
    POST_TO_BASE_POST_MODEL,
    CREATE_POST_REQUEST_TO_CREATE_MODEL,
    POST_REACTIONS_COUNT_MODEL_TO_POST_REACTIONS_COUNT_RESPONSE,
    UPDATE_POST_REQUEST_TO_UPDATE_MODEL,
    BASE_POST_MODEL_TO_POST_MODEL,
    CREATE_POST_MODEL_TO_CREATE_ENTITY;
}