name: Deploy Monolith to testing stage

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true
      release-version:
        description: 'Release version number'
        required: true
      ticket:
        description: 'Release ticket number in tracker'
        default: 'Without ticket'
        required: false

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Show deploy ticket
      run: echo "Deploy ticket ${{ github.event.inputs.name }}"
  deploy:
   runs-on: ubuntu-latest
   
   steps:
   - uses: actions/checkout@v3
   - name: Build docker image
     run: docker build . --file Dockerfile --tag mono-backend:${{ github.event.inputs.release-version }}
   - name: Push docker image to Yandex.Cloud registry
     run: docker push mono-backend:${{ github.event.inputs.release-version }}
